name: 🚀 Release

on:
  workflow_dispatch:

jobs:
  lint:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/linter.yml

  build:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/build.yml

  perfom-release:
    if: github.ref == 'refs/heads/main'
    needs:
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release project
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.0.0
          branch: main
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/npm
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
